config/routes.rb
Rails.application.routes.draw do
root to: 'pages#home'
resources :restaurants
resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
    @contact = ["100 Test St","647 800-0000","test@test.com"]
  end

  def about
  end
  def goodbye
    @goodbye = "Goodbye"
  end
  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController


  def index
    @restaurants = Restaurant.all
  end

  def home
   @home
  end

  def new
   @restaurant = Restaurant.new
  end

  def show
  @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    render 'show'
  end


  def create
    @resturant = Restaurant.new(restaurant_params)
    @resturant.save
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(
    :name, :address, :category, :stars)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
      @users = User.all
    end

    def home
     @home
    end

    def new
     @user = User.new
    end

    def create
      @user = User.new(user_params)
      @user.save
    end

    def show
      @user = User.find(params[:id])
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      @user.update(user_params)
      render 'show'
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to users_path
    end


  private

  def user_params
    params.require(:user).permit(
    :name, :age, )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thespoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>The spoon</h1>
    <%= yield %>
    <%= link_to 'Home', root_path %>
    <%= link_to 'restaurants', restaurants_path %>
    <%= link_to 'users', users_path %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<h3>Address</h3>
<p><%= @contact[0] %></p>
<h3>Phone Number</h3>
<p><%= @contact[1] %></p>
<h3>Email</h3>
<p><%= @contact[2] %></p>

app/views/pages/goodbye.html.erb
<h1><%= @goodbye %></h1>

app/views/pages/home.html.erb
<h1>home page<h1>

app/views/restaurants/_form.html.haml
= form_for(@restaurant) do |f|

  = f.label :name
  = f.text_field :name

  = f.label :address
  = f.text_field :address

  = f.label :category
  = f.text_field :category

  = f.label :stars
  = f.text_field :stars

  = f.submit 

app/views/restaurants/edit.html.haml
= render 'form'

app/views/restaurants/index.html.haml
%h2
  =Restaurant
%ul
  - @restaurants.each do |restaurant|
    %h3
      %li= link_to restaurant[:name], restaurant_path(restaurant)
      %li= restaurant[:address]
      %li= restaurant[:category]
      %li= restaurant[:stars]

= link_to 'New Restaurant', new_restaurant_path

app/views/restaurants/new.html.haml
= render 'form'

app/views/restaurants/show.html.haml
%h3= @restaurant[:name]

%p
  ="Adress: #{@restaurant[:address]}"
  ="Category:#{@restaurant[:category]}"
  ="Stars: #{@restaurant[:stars]}"

= link_to 'Edit', edit_restaurant_path
= link_to 'Delete', restaurant_path(@restaurant),method: :delete
%br

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.number_field :age %>

  <%= f.submit %>

<% end %>

app/views/users/index.html.erb
<h2>Users</h2>

  <% @users.each do |user| %>
    <h3/><%= link_to user[:name],user_path(user)%></h3>
    <p><%= user[:age] %></P>
  <% end %>


<%= link_to 'Add User', new_user_path %>
<br/>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.number_field :age %>

  <%= f.submit %>

<% end %>

app/views/users/show.html.erb
<h3><%= @user[:name] %></h3>
<p>Age:<%= @user[:age] %></p>

<%= link_to 'Edit', edit_user_path %>
<%= link_to 'Delete', user_path(@user),method: :delete %>
<br/>